#!/bin/bash
echo "🔍 CHECKING RAILWAY SERVICE SETTINGS"
echo "====================================="
echo ""
echo "Your Project: charismatic-miracle"
echo "Current Domain: web-production-6fffd.up.railway.app"
echo ""
echo "📋 Manual Check Required:"
echo "1. Visit: https://railway.app/project/charismatic-miracle"
echo "2. Click on your service (probably 'web')"
echo "3. Go to 'Settings' tab"
echo "4. Check:"
echo "   - 'Port' setting (should be 8080 or 8000)"
echo "   - 'Start Command' (should be: python pouchon_bot.py)"
echo ""
echo "💡 Common Solutions:"
echo "• If port is different, change it to 8080"
echo "• If start command is wrong, set to: python pouchon_bot.py"
echo "• Save changes and redeploy"
